In [19]:
import pandas as pd

def excel_to_dataframe(file_path, sheet = "Solution"):
    """
    Converts an Excel file into a Pandas DataFrame.
    
    Args:
    - file_path (str): The path to the Excel file.
    
    Returns:
    - df (DataFrame): The Pandas DataFrame containing the data from the Excel file.
    """
    try:
        # Read the Excel file into a DataFrame
        df = pd.read_excel(file_path, sheet_name=sheet, skiprows=0)
        return df
    except Exception as e:
        print("An error occurred while reading the Excel file:", e)
        return None

# Example usage:
file_path = 'C:/Users/nilst/Documents/EPFL/BA_4/ppchem/Project/UserData.xlsx'
df = excel_to_dataframe(file_path)
print(df.head())

def name2Ksp(df, salt_name):
    """
    Access the solubility product constant (Ksp) of a salt based on its name.
    
    Args:
    - df (DataFrame): The Pandas DataFrame containing the data.
    - salt_name (str): The name of the salt.
    
    Returns:
    - solubility (float): The solubility product constant (Ksp) of the salt.
    """
    try:
        # Access the solubility based on the name of the salt
        solubility = df.loc[df['Salt Name'] == salt_name, 'Ksp (20°C)'].values[0]
        return solubility
    except Exception as e:
        print("An error occurred while accessing the solubility:", e)
        return None
    
def formula2Ksp(df, formula):
    """
    Access the solubility product constant (Ksp) of a salt based on its name.
    
    Args:
    - df (DataFrame): The Pandas DataFrame containing the data.
    - salt_name (str): The name of the salt.
    
    Returns:
    - solubility (float): The solubility product constant (Ksp) of the salt.
    """
    try:
        # Access the solubility based on the name of the salt
        solubility = df.loc[df['Chemical formula'] == formula, 'Ksp (20°C)'].values[0]
        return solubility
    except Exception as e:
        print("An error occurred while accessing the solubility:", e)
        return None
    
# Example usage:  
salt_name = 'Potassium nitrate'
print(name2Ksp(df, salt_name))

                        Salt Name Chemical formula  Molar mass [g/mol]  \
0               Potassium nitrate             KNO3              101.10
1                 Calcium nitrate         Ca(NO3)2              164.09
2               Magnesium sulfate            MgSO4              120.37
3  Potassium dihydrogen phosphate           KH2PO4              136.09
4   Ammonium dihydrogen phosphate       (NH4)H2PO4              115.03

   Ksp (20°C)  pKa (20°C)  Input [g/L]
0         NaN         NaN        0.493
1         NaN         NaN        0.945
2         NaN         NaN        0.493
3         NaN         NaN        0.136
4         NaN         NaN        0.000
nan

In [21]:
solution_df = excel_to_dataframe(file_path, "Solution")
plant_df = excel_to_dataframe(file_path, "Plants")

solution_df

,Salt Name,Chemical formula,Molar mass [g/mol],Ksp (20°C),pKa (20°C),Input [g/L],Volume [L]
0,Potassium nitrate,KNO3,101.10,NaN,NaN,0.493000,10.0
1,Calcium nitrate,Ca(NO3)2,164.09,NaN,NaN,0.945000,NaN
2,Magnesium sulfate,MgSO4,120.37,NaN,NaN,0.493000,NaN
3,Potassium dihydrogen phosphate,KH2PO4,136.09,NaN,NaN,0.136000,NaN
4,Ammonium dihydrogen phosphate,(NH4)H2PO4,115.03,NaN,NaN,0.000000,NaN
5,Boric acid,H3BO3,61.83,NaN,NaN,0.046500,NaN
6,Manganese chloride,MnCl2,125.84,NaN,NaN,0.022300,NaN
7,Zinc sulfate,ZnSO4,161.44,NaN,NaN,0.008600,NaN
8,Copper sulfate,CuSO4,159.61,NaN,NaN,0.000025,NaN
9,Ammonium molybdate,(NH4)6Mo7O24,1236.00,NaN,NaN,0.000025,NaN
10,Fe(III) EDTA,C10H12FeN2O8,344.06,NaN,NaN,0.037300,NaN

In [ ]:
def create_solutiondict(solution_df):
    solution_dict = {}
    for i in range(len(solution_df)):
        solution_dict[solution_df.iloc[i,0]] = solution_df.iloc[i,1]
    return solution_dict

# Example usage:
solution_dict = create_solutiondict(solution_df)